---
- name: Install Java, Maven, NPM, Docker, Terraform, and SonarQube
  hosts: localhost
  become: yes

  tasks:
    - name: Update apt packages
      apt:
        update_cache: yes

    - name: Install Java
      apt:
        name: openjdk-17-jdk
        state: present
        update_cache: yes

    - name: Install Maven
      apt:
        name: maven
        state: present

    - name: Install npm
      apt:
        name: npm
        state: present

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Install curl and unzip
      apt:
        name:
          - curl
          - unzip
        state: present

    - name: Enable and start Docker
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Install Terraform
      shell: |
        wget -O- https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
        echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
        sudo apt update && sudo apt install terraform -y
      args:
        executable: /bin/bash


    # SonarQube setup
   
    - name: Pull SonarQube Docker image
      community.docker.docker_image:
        name: sonarqube
        tag: latest
        source: pull

    - name: Run SonarQube container
      community.docker.docker_container:
        name: sonarqube
        image: sonarqube:latest
        state: started
        restart_policy: always
        ports:
          - "9000:9000"