trigger: none

# Define the build agent pool
pool:
  name: "Sachin_agent"

# Global variables
variables:
  azureServiceConnection: '4733385e-ac73-405b-8349-e777e3a42950'
  resourceGroup: 'Java-Reac-Project'
  vmName: 'ProjectVM'
  storageAccount: 'tfstateaksacr'
  containerName: 'aksacrtfstate'
  tfstateKey: 'teransi.terraform.tfstate'

# -----------------------
# STAGE 1: TERRAFORM DEPLOYMENT
# -----------------------
stages:
- stage: Terraform_Deploy
  displayName: "Terraform Infrastructure Deployment"
  jobs:
  - job: Terraform
    displayName: "Run Terraform Tasks"
    steps:
    - task: TerraformTask@5
      displayName: 'Terraform : init'
      inputs:
        command: init
        environmentServiceNameAzureRM: $(azureServiceConnection)
        backendType: 'azurerm'
        backendServiceArm: $(azureServiceConnection)
        backendAzureRmResourceGroupName: 'krishna-kiran'
        backendAzureRmStorageAccountName: $(storageAccount)
        backendAzureRmContainerName: $(containerName)
        backendAzureRmKey: $(tfstateKey)

    - task: TerraformTask@5
      displayName: 'Terraform : plan'
      inputs:
        command: plan
        environmentServiceNameAzureRM: $(azureServiceConnection)

    - task: TerraformTask@5
      displayName: 'Terraform : apply'
      inputs:
        command: apply
        environmentServiceNameAzureRM: $(azureServiceConnection)
        autoApprove: true

# -----------------------
# STAGE 2: CONFIGURE VM WITH ANSIBLE
# -----------------------
- stage: Configure_VM
  displayName: "Install Ansible on Azure VM"
  dependsOn: Terraform_Deploy
  condition: succeeded()   # Run only if Terraform succeeded
  jobs:
  - job: Install_Ansible
    displayName: "Use Azure CLI to install Ansible"
    steps:
    - task: AzureCLI@2
      displayName: "Install Ansible via VM Extension"
      inputs:
        azureSubscription: $(azureServiceConnection)  # Service connection, not subscription ID
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az vm extension set \
            --resource-group $(resourceGroup) \
            --vm-name $(vmName) \
            --name customScript \
            --publisher Microsoft.Azure.Extensions \
            --settings '{
              "commandToExecute": "sudo apt-get update -y && sudo apt-get install -y software-properties-common && sudo add-apt-repository --yes --update ppa:ansible/ansible && sudo apt-get install -y ansible"
            }'